name: Mi primera integracion continua

on: push

jobs:
  compilar: 
    runs-on: ubuntu-latest
    steps: 
      - name: Descargar repositorio
        uses: actions/checkout@v2
      - name: Instalar jDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"     
      - name: Contruir con maven
        run: mvn clean package -DskipTests
      - name: Guardar paquete generado para el trabajo de despliegue
        uses: actions/upload-artifact@v4
        with:
          name: movicards-java
          path: "${{github.workspace}}/target/*.jar"

  probar:
    needs: compilar
    runs-on: ubuntu-latest
    steps: 
      - name: pruebas
        run: echo "pruebas"

  controlar_calidad:
    needs: probar
    runs-on: ubuntu-latest
    steps:
      - name: calidad
        run: echo "calidad"

  desplegar:
    needs: controlar_calidad
    runs-on: ubuntu-latest
    steps: 
      - name: despliegue
        run: echo "despliegue"
  